cat("SIMPLE LINEAR REGRESSION")
simple_LR <- lm(mpg ~ ms, data = mtcars)
intercept1 <- round(as.numeric(simple_LR$coefficients[1]), 2)
slope1 <- round(as.numeric(simple_LR$coefficients[2]), 2)
simple_LR_eq <- paste("mpg =", intercept1, "+", slope1, "* ms")
cat("Generated Model is: ")
cat(simple_LR_eq)
cat("Summary of the Model:")
print(summary(simple_LR))

plot(mtcars$ms, mtcars$mpg, col = "blue", main = "ms & mpg Regression")
abline(simple_LR, col = "red", lwd = 2)
xlabel <- "Horse Power"
ylabel <- "Miles Per Gallon"
title(main = "ms & mpg Regression", xlab = xlabel, ylab = ylabel)

cat("MULTIPLE LINEAR REGRESSION")
multiple_LR <- lm(mpg ~ ms + disp + wt, data = mtcars)
intercept2 <- round(as.numeric(multiple_LR$coefficients[1]), 2)
slope_ms <- round(as.numeric(multiple_LR$coefficients[2]), 2)
slope_disp <- round(as.numeric(multiple_LR$coefficients[3]), 2)
slope_wt <- round(as.numeric(multiple_LR$coefficients[4]), 2)
multiple_LR_eq <- paste("mpg =", intercept2, "+", slope_hp, "* ms", "+", slope_disp, "* disp", "+", slope_wt, "* wt")
cat("Generated Model is: ")
cat(multiple_LR_eq)
cat("Summary of the Model:")
print(summary(multiple_LR))
